services:
  - type: web
    name: oppvenuz-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        fromDatabase: false
        value: your_secret_key_here
      - key: DB_NAME
        fromDatabase: false
        value: your_db_name_here
      - key: DB_USER
        fromDatabase: false
        value: your_db_user_here
      - key: DB_PASSWORD
        fromDatabase: false
        value: your_db_password_here
      - key: DB_HOST
        fromDatabase: false
        value: your_db_host_here
      - key: DB_PORT
        fromDatabase: false
        value: your_db_port_here
